### ISSUE TITLE
No email is received from commit-email.info

### ISSUE THREAD

**Issue by abetomo** [kou/commit-email.info#17]
#15 has been resolved and the webhook now returns a 200 response, but I have not received a commit email.
Probably after #15, I stopped receiving one.
Do I just subscribe again?

**Comment by kou** [comment]
No. It's an internal error.

I needed to change `TimeoutError` to `Timeout::Error` in QuickML.

**Comment by abetomo** [comment]
I received a commit email. Thanks.
